// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/omarvides/goalearn/design
// --out=$(GOPATH)/src/github.com/omarvides/goalearn
// --version=v1.1.0-dirty
//
// API "user": Application User Types
//
// The content of this file is auto-generated, DO NOT MODIFY

package client
